import asyncio
import json
import os
import subprocess
from datetime import datetime
from datetime import time as dt_time
from datetime import timedelta
from pathlib import Path

import decky_plugin


class Plugin:
    def __init__(self):
        self.plugin_dir = Path(__file__).parent
        self.script_path = self.plugin_dir / "charge-scheduler.sh"
        self.log_path = Path.home() / ".local/share/charge-scheduler.log"
        self.data_dir = Path(os.environ["DECKY_PLUGIN_RUNTIME_DIR"])
        self.config_path = self.data_dir / "charge-scheduler.conf"
        self.settings_file = self.data_dir / "settings.json"
        decky_plugin.logger.info(f"Using runtime directory: {self.data_dir}")

    def _default_cfg(self) -> dict:
        return {
            "MODE": "schedule",
            "START_HOUR": 8,
            "START_MINUTE": 0,
            "DURATION_MINUTES": 60,
            "CHARGE_LIMIT": 80,
            "SCHEDULE_DESCRIPTION": "Default configuration",
        }

    def _read_cfg(self) -> dict:
        try:
            if self.settings_file.exists():
                with open(self.settings_file, "r") as f:
                    config = json.load(f)
                decky_plugin.logger.info(f"Loaded config from {self.settings_file}: {config}")
                return config
            else:
                default_config = self._default_cfg()
                self._write_cfg(**default_config)
                decky_plugin.logger.info(f"Created default config at {self.settings_file}: {default_config}")
                return default_config
        except Exception as e:
            decky_plugin.logger.error(f"Error reading config from {self.settings_file}: {e}")
            raise Exception(f"Configuration read failed: {e}")

    def _write_cfg(self, mode: str, sh: int, sm: int, dur: int, limit: int, desc: str) -> None:
        try:
            config_data = {
                "MODE": mode,
                "START_HOUR": sh,
                "START_MINUTE": sm,
                "DURATION_MINUTES": dur,
                "CHARGE_LIMIT": limit,
                "SCHEDULE_DESCRIPTION": desc,
            }

            self.data_dir.mkdir(parents=True, exist_ok=True)

            with open(self.settings_file, "w") as f:
                json.dump(config_data, f, indent=2)

            decky_plugin.logger.info(f"Saved config to {self.settings_file}: {config_data}")
        except Exception as e:
            decky_plugin.logger.error(f"Error saving config to {self.settings_file}: {e}")
            raise Exception(f"Configuration write failed: {e}")

        try:
            text = f"""# Steam Deck Charge Scheduler Configuration
# This file is automatically generated from plugin settings
# DO NOT EDIT MANUALLY - changes will be overwritten

# Operating mode: schedule, always_full, always_limit
MODE={mode}

# Schedule configuration (for "schedule" mode)
START_HOUR={sh}
START_MINUTE={sm}
DURATION_MINUTES={dur}

# Default charge limit (50-100%)
CHARGE_LIMIT={limit}

# Schedule description (optional, for display purposes)
SCHEDULE_DESCRIPTION="{desc}"
"""
            with open(self.config_path, "w") as f:
                f.write(text)
            decky_plugin.logger.info(f"Generated runtime config file: {self.config_path}")
        except Exception as e:
            decky_plugin.logger.error(f"Error writing runtime config: {e}")
            raise Exception(f"Runtime config write failed: {e}")

    async def _tail_logs(self, n: int) -> list[str]:
        if not self.log_path.exists():
            return []
        with open(self.log_path, "r") as f:
            lines = f.readlines()
        return [ln.strip() for ln in lines[-n:]]

    async def get_config(self) -> dict:
        decky_plugin.logger.info("Request received")
        try:
            config = self._read_cfg()
            decky_plugin.logger.info(f"Returning config: {config}")
            return config
        except Exception as e:
            decky_plugin.logger.error(f"Error: {e}")
            raise Exception(f"Get config failed: {e}")

    async def set_config(
        self,
        mode: str,
        start_hour: int,
        start_minute: int,
        duration: int,
        charge_limit: int,
        description: str = "",
    ) -> dict:
        decky_plugin.logger.info(
            f"Request: mode={mode}, time={start_hour}:{start_minute}, duration={duration}, limit={charge_limit}%"
        )

        try:
            if mode not in ["schedule", "always_full", "always_limit"]:
                error_msg = "Invalid mode"
                decky_plugin.logger.error(f"{error_msg}: {mode}")
                return {"success": False, "error": error_msg}
            if not (0 <= start_hour <= 23) or not (0 <= start_minute <= 59):
                error_msg = "Invalid time values"
                decky_plugin.logger.error(f"{error_msg}: {start_hour}:{start_minute}")
                return {"success": False, "error": error_msg}
            if not (5 <= duration <= 480):
                error_msg = "Duration must be 5–480 minutes"
                decky_plugin.logger.error(f"{error_msg}: {duration}")
                return {"success": False, "error": error_msg}
            if not (50 <= charge_limit <= 100):
                error_msg = "Charge limit must be 50–100"
                decky_plugin.logger.error(f"{error_msg}: {charge_limit}")
                return {"success": False, "error": error_msg}

            try:
                os.chmod(self.script_path, 0o755)
                decky_plugin.logger.info("Script permissions set")
            except Exception as e:
                decky_plugin.logger.warning(f"Could not set script permissions: {e}")

            self._write_cfg(mode, start_hour, start_minute, duration, charge_limit, description)
            decky_plugin.logger.info(
                f"Config saved successfully: {mode} {start_hour}:{start_minute} {duration}m {charge_limit}%"
            )
            return {"success": True, "message": "Configuration saved successfully"}
        except Exception as e:
            decky_plugin.logger.error(f"Exception: {e}")
            return {"success": False, "error": str(e)}

    async def get_status(self) -> dict:
        decky_plugin.logger.info("Request received")
        try:
            cfg = self._read_cfg()
            decky_plugin.logger.info(f"Config loaded: {cfg}")

            logs = await self._tail_logs(20)
            decky_plugin.logger.info(f"Found {len(logs)} log entries")

            mode = cfg.get("MODE", "schedule")
            if mode == "schedule":
                # schedule mode, show the appropriate current limit based on time
                sh = int(cfg.get("START_HOUR", 8))
                sm = int(cfg.get("START_MINUTE", 0))
                dur = int(cfg.get("DURATION_MINUTES", 60))
                now = datetime.now()
                start = datetime.combine(now.date(), dt_time(sh, sm))
                end = start + timedelta(minutes=dur)

                if now >= start and now < end:
                    current = "100%"
                    decky_plugin.logger.info(f"In charging window, showing 100%")
                else:
                    current = f"{cfg.get('CHARGE_LIMIT', 80)}%"
                    decky_plugin.logger.info(f"Outside charging window, showing configured limit: {current}")
            elif mode == "always_full":
                current = "100%"
                decky_plugin.logger.info(f"Always full mode: {current}")
            else:
                # always_limit mode,
                current = f"{cfg.get('CHARGE_LIMIT', '?')}%"
                decky_plugin.logger.info(f"Always limit mode: {current}")

            if mode == "schedule":
                time_range = f"{start.strftime('%H:%M')} - {end.strftime('%H:%M')}"
                if now < start:
                    next_change = f"Full charge ({time_range})"
                elif now < end:
                    next_change = f"Limited charge at {end.strftime('%H:%M')} (from {time_range})"
                else:
                    next_change = f"Full charge {time_range} (tomorrow)"
            elif mode == "always_full":
                next_change = "Always charging to 100%"
            else:
                next_change = "Always limited"

            return {
                "current_limit": current,
                "next_change": next_change,
                "config": cfg,
                "script_path": str(self.script_path),
                "config_file_exists": self.config_path.exists(),
            }
        except Exception as e:
            decky_plugin.logger.error(f"get_status error: {e}")
            raise Exception(f"Get status failed: {e}")

    async def apply_schedule_now(self) -> dict:
        try:
            # Note: Using sh instead of bash to avoid readline compatibility issues
            result = subprocess.run(
                ["sh", str(self.script_path), "reload"],
                capture_output=True,
                text=True,
                timeout=30,
                env={"PATH": "/usr/bin:/bin", "TERM": "dumb", "HOME": os.path.expanduser("~")},
            )
            if result.returncode == 0:
                decky_plugin.logger.info("Schedule applied")
                return {"success": True}
            else:
                decky_plugin.logger.error(f"Script failed: {result.stderr}")
                return {"success": False, "error": result.stderr or result.stdout}
        except subprocess.TimeoutExpired:
            return {"success": False, "error": "Operation timed out"}
        except Exception as e:
            decky_plugin.logger.error(f"apply_schedule_now error: {e}")
            return {"success": False, "error": str(e)}

    async def get_scheduler_status(self) -> dict:
        """Check if the background scheduler is running"""
        try:
            scheduler_running = getattr(self, "scheduler_running", False)
            scheduler_task = getattr(self, "scheduler_task", None)

            if scheduler_task and not scheduler_task.done():
                return {
                    "scheduler_running": True,
                    "scheduler_active": True,
                    "message": "Background scheduler is running",
                }
            elif scheduler_running:
                return {
                    "scheduler_running": True,
                    "scheduler_active": False,
                    "message": "Scheduler configured but not active",
                }
            else:
                return {
                    "scheduler_running": False,
                    "scheduler_active": False,
                    "message": "Background scheduler is not running",
                }
        except Exception as e:
            decky_plugin.logger.error(f"get_scheduler_status error: {e}")
            raise Exception(f"Get scheduler status failed: {e}")

    async def scheduler_loop(self):
        """Background task that runs the schedule check every 5 minutes"""
        decky_plugin.logger.info("Background scheduler started")

        while self.scheduler_running:
            try:
                decky_plugin.logger.debug("Running scheduled charge check...")
                await self.check_and_apply_schedule()

                await asyncio.sleep(300)

            except asyncio.CancelledError:
                decky_plugin.logger.info("Scheduler cancelled")
                break
            except Exception as e:
                decky_plugin.logger.error(f"Scheduler error: {e}")
                await asyncio.sleep(60)

        decky_plugin.logger.info("Background scheduler stopped")

    async def check_and_apply_schedule(self):
        """Check current schedule and apply appropriate charge limit"""
        try:
            result = subprocess.run(
                ["sh", str(self.script_path), "schedule"],
                capture_output=True,
                text=True,
                timeout=30,
                env={"PATH": "/usr/bin:/bin", "TERM": "dumb", "HOME": os.path.expanduser("~")},
            )

            if result.returncode == 0:
                decky_plugin.logger.debug("Schedule check completed successfully")
            else:
                decky_plugin.logger.warning(f"Schedule check failed: {result.stderr}")

        except subprocess.TimeoutExpired:
            decky_plugin.logger.error("Schedule check timed out")
        except Exception as e:
            decky_plugin.logger.error(f"Error running schedule check: {e}")

    async def _main(self):
        decky_plugin.logger.info("Charge Scheduler backend started")

        self.scheduler_running = True
        self.scheduler_task = None

        try:
            os.chmod(self.script_path, 0o755)
        except Exception:
            pass

        try:
            self.scheduler_task = asyncio.create_task(self.scheduler_loop())
            decky_plugin.logger.info("Background scheduler task created")
        except Exception as e:
            decky_plugin.logger.error(f"Failed to start scheduler task: {e}")

    async def _unload(self):
        decky_plugin.logger.info("Charge Scheduler backend stopping...")

        if hasattr(self, "scheduler_running"):
            self.scheduler_running = False

        if hasattr(self, "scheduler_task") and self.scheduler_task:
            try:
                self.scheduler_task.cancel()
                await self.scheduler_task
            except asyncio.CancelledError:
                decky_plugin.logger.debug("Scheduler task cancelled during unload")
            except Exception as e:
                decky_plugin.logger.error(f"Error stopping scheduler: {e}")

        decky_plugin.logger.info("Charge Scheduler backend stopped")

    async def _uninstall(self):
        decky_plugin.logger.info("Charge Scheduler backend uninstalled")

    async def _migration(self):
        decky_plugin.logger.info("Charge Scheduler migration: none")
